name: Docker Hub

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1.2.0

    - name: Extract tag name
      shell: bash
      run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
      id: extract_tag_name

    - name: Build Jupyter Hub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        dockerfile: Dockerfile
        name: gordonwatts/uw-gwatts-notebook-server:${{ steps.extract_tag_name.outputs.imagetag }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: "${GITHUB_REF##*/}"
